name: Integraci贸n continua con Node.js

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Obtener hora de inicio
      id: inicio
      uses: nanzm/get-time-action@v1.0
      with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'
    - name: Mostrar hora de inicio
      run: echo "Hora de inicio ${{ steps.inicio.outputs.time }}"
    - name: Setup...
      uses: actions/setup-node@v1
      with: 
        node-version: ${{matrix.node-version}}
    - name: npm install, build and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Obtener hora de finalizaci贸n
      id: fin
      uses: nanzm/get-time-action@v1.0
      with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'
    - name: Mostrar hora de finalizaci贸n
      run: echo "Hora de finalizaci贸n ${{ steps.fin.outputs.time }}"