name: Integración continua con Node.js

on: 
  push:
    branches: [master]

jobs:
  ci_to_master:
    runs-on: ubuntu-lastest
    name: Github Actions
    steps:
      - name: Hora de inicio
      - id: inicio
      - run: echo "Hora de inicio ${{ steps.inicio.outputs.time }}"
      - name: Comprobando...
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - with: node-version:12
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Hora de finalización
      - id: fin
      - run: echo "Hora de finalización ${{ steps.fin.outputs.time }}"